### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by daniellionel01** [team-plain/docs#13]
Path: /api-reference/ui-components

The following links are broken:
- https://app.plain.com/developer/customer-cards-playground/
- https://app.plain.com/developer/custom-timeline-entry-playground/

<img width="1493" alt="Screenshot 2023-12-06 at 16 27 26" src="https://github.com/team-plain/docs/assets/35135912/390a0698-51b4-4b57-8116-8b9d556734b5">

<img width="1507" alt="Screenshot 2023-12-06 at 16 27 39" src="https://github.com/team-plain/docs/assets/35135912/4da495ae-4c1a-4d99-b49e-7ebeba85b359">

**Comment by mattvagni** [comment]
Thanks for reporting @daniellionel01 !

I think was fixed in https://github.com/team-plain/docs/pull/18 right @DLeyland ?

**Comment by DLeyland** [comment]
Yep this should be fixed now
