### ISSUE TITLE
`attachment:read` doesn't exist 

### ISSUE THREAD

**Issue by ghobaty** [team-plain/docs#35]
Path: /api-reference/graphql/messaging/reply-email
<img width="698" alt="Screenshot 2024-04-05 at 18 45 21" src="https://github.com/team-plain/docs/assets/6379163/81b77eca-ee73-4c79-9468-717a02781594">

Plain Dashboard:
<img width="513" alt="Screenshot 2024-04-05 at 18 45 02" src="https://github.com/team-plain/docs/assets/6379163/bf06a627-80bb-494c-ba11-9e9fb1d4c03d">

**Comment by presmihaylov** [comment]
Hey @ghobaty thanks for raising this!

Will be fixed as part of #37
